baseURL = "https://example.github.io/"
languageCode = "zh-cn"
title = "chengcheng „ÅÆ Web"
theme = "PaperMod"
[params.assets]
  customCSS = ["css/extended.css"]

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
